### ISSUE TITLE
Finish repository migration

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ibc#538]
Per discussion.

- [x] Reorganise this repository, with subdirectories corresponding to the five semantic categories:
  1. Core IBC: ICS 2, 3, 4
  2. Light client (validity predicate) specifications: ICS 7, 8, etc. etc.
  3. Application framework integration points: ICS 5, 23, 24, 25, 26
  4. Relayer system, queries, events: ICS 18 (debatable whether this should be separate from core protocol)
  5. Application protocols: ICS 20, 27, etc. (more to come)
- [x] Transfer documents and issues from prior ICS repository
- [x] Create labels & reorganise existing issues
- [x] Clarify contribution guidelines & expected reviewers (may vary for different semantic categories)
- [ ] Migrate each specification document to the new format - https://github.com/cosmos/ibc/issues/40 - per the template, one-by-one
  - Clarify description, add/clarify invariants, add motivating example
  - This should be done at the same time as review (perhaps review of the implementation as well)
  - Potentially certain documents could be combined or split as makes most sense
- [ ] Update PDF generation scripts, if desired
- [ ] Integrate Informal's work (alongside model-based tests?)
- [ ] Release alongside migrated Go code
- [ ] Figure out additional topics that should be discussed in this repository and add them
  - For example, relayer event standards & HTTP/gRPC query API
